### ISSUE TITLE
Style stuff

### ISSUE THREAD

**Issue by glemaitre** [amueller/scipy-2018-sklearn#13]
I see that we are using:

```python
import numpy as np
np.bincount(iris.target)
array([50, 50, 50])
```

I agree that this is much faster than what I will propose 
but I find the output of `Counter` a bit more didactic.

```python
from collections import Counter
Counter(iris.target)
Counter({0: 50, 1: 50, 2: 50})
```

@amueller Are you against this change for some reason?

**Comment by glemaitre** [comment]
The advantage to me is that you get the key as well.

**Comment by amueller** [comment]
hm... I never use counter and always use bincount but maybe counter would be smarter.   Usually I try to go towards best practices but I think being didactic might be better in this case.

**Comment by glemaitre** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I can make a PR and show the output. Do you see anything else to be changed or might be improved?                                                                                                                                                                        Sent from my phone - sorry to be brief and potential misspell.

**Comment by amueller** [comment]
your email responses have weird html in them.

Honestly I didn't have the time to go through the tutorial yet.

**Comment by amueller** [comment]
(I went down from 300 unread emails yesterday after a long weekend off to 30 unread emails today. maybe tomorrow I get work done)

**Comment by glemaitre** [comment]
@ogrisel prefer to not use `Counter` since it is not efficient which is fine as well
