### ISSUE TITLE
Titanic example

### ISSUE THREAD

**Issue by glemaitre** [amueller/scipy-2018-sklearn#16]
Do you think that we can make an example with the column transformer to illustrate the benefit on an extra section which is just for demo?

**Comment by amueller** [comment]
I'm offline till Monday.

**Comment by amueller** [comment]
sorry I don't follow. And we can't really rely on 0.20 being released, right?

**Comment by glemaitre** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  We wanted to make a pre release but it is true that it could complicated.                                                                                                                                                                         Sent from my phone - sorry to be brief and potential misspell.

**Comment by amueller** [comment]
yeah no pre-release for the tutorial. that spells disaster.
