### ISSUE TITLE
Typo in the repo description

### ISSUE THREAD

**Issue by yassineAlouini** [amueller/scipy-2018-sklearn#20]
This is a minor issue. 
The repo description should be `Scipy 2018 scikit-learn tutorial by Guillaume Lemaitre and Andreas Mueller` instead of `
Scipy 2017 scikit-learn tutorial by Guillaume Lemaitre and Andreas Mueller`. :)

**Comment by amueller** [comment]
wanna send a PR?

**Comment by yassineAlouini** [comment]
Would love to (even though it seems overkill) but I am not sure if it is even possible to do it for the Github description section (it isn't part of the .git folder). :smile: 
What do you think?

**Comment by amueller** [comment]
oh you're right ;)
